In [1]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

# Remplacez 'Mon_Dossier/mon_fichier.csv' par le chemin réel de votre fichier sur Google Drive
file_path = '/content/drive/My Drive/formation_personnelle/data_csv/transactions.csv'

try:
    df = pd.read_csv(file_path, sep=";")
    print(f"Fichier '{file_path}' chargé avec succès.")
    display(df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier '{file_path}' n'a pas été trouvé. Veuillez vérifier le chemin.")
except Exception as e:
    print(f"Une erreur est survenue lors du chargement du fichier: {e}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Fichier '/content/drive/My Drive/formation_personnelle/data_csv/transactions.csv' chargé avec succès.

  id_prod                 date session_id client_id
0  2_1236  2021-04-05 19:10:00     T_6675    6_2893
1  Z_5626  2021-10-08 00:51:00     4_6032    6_1023
2  B_1540  2021-07-14 05:51:00     3_5954    6_1525
3  X_1818  2021-06-23 21:55:00     T_4019    6_1908
4   Z_878  2021-03-11 15:22:00     3_4224    5_5523

In [4]:
transaction = df

In [6]:
#Si par exemple on veut gardrer les valeurs qui viennent après le underscore de la colonne id_prod
transaction['id_prod'].apply(lambda x: x.split('_')[1])

0      1236
1      5626
2      1540
3      1818
4       878
       ...
295    8569
296    9593
297    4511
298    2908
299     819
Name: id_prod, Length: 300, dtype: object

In [14]:
#Pour extraire l'année et la stocker dans une nouvelle colonne
transaction['annees'] = transaction['date'].apply(lambda x: x.split('-')[0])
transaction

    id_prod                 date session_id client_id annees date_complete
0    2_1236  2021-04-05 19:10:00     T_6675    6_2893   2021    2021-04-05
1    Z_5626  2021-10-08 00:51:00     4_6032    6_1023   2021    2021-10-08
2    B_1540  2021-07-14 05:51:00     3_5954    6_1525   2021    2021-07-14
3    X_1818  2021-06-23 21:55:00     T_4019    6_1908   2021    2021-06-23
4     Z_878  2021-03-11 15:22:00     3_4224    5_5523   2021    2021-03-11
..      ...                  ...        ...       ...    ...           ...
295  X_8569  2021-08-12 17:32:00      S_108    6_2726   2021    2021-08-12
296  2_9593  2021-02-01 04:43:00     3_2527    D_8089   2021    2021-02-01
297  A_4511  2021-11-18 18:32:00      3_825     D_634   2021    2021-11-18
298  X_2908  2021-06-28 02:08:00     3_3711    D_5776   2021    2021-06-28
299   1_819  2021-06-04 07:51:00     T_5144    C_1448   2021    2021-06-04

[300 rows x 6 columns]

In [12]:
transaction['date_complete'] = transaction['date'].apply(lambda x: x.split(' ')[0])
transaction

    id_prod                 date session_id client_id annees date_complete
0    2_1236  2021-04-05 19:10:00     T_6675    6_2893   2021    2021-04-05
1    Z_5626  2021-10-08 00:51:00     4_6032    6_1023   2021    2021-10-08
2    B_1540  2021-07-14 05:51:00     3_5954    6_1525   2021    2021-07-14
3    X_1818  2021-06-23 21:55:00     T_4019    6_1908   2021    2021-06-23
4     Z_878  2021-03-11 15:22:00     3_4224    5_5523   2021    2021-03-11
..      ...                  ...        ...       ...    ...           ...
295  X_8569  2021-08-12 17:32:00      S_108    6_2726   2021    2021-08-12
296  2_9593  2021-02-01 04:43:00     3_2527    D_8089   2021    2021-02-01
297  A_4511  2021-11-18 18:32:00      3_825     D_634   2021    2021-11-18
298  X_2908  2021-06-28 02:08:00     3_3711    D_5776   2021    2021-06-28
299   1_819  2021-06-04 07:51:00     T_5144    C_1448   2021    2021-06-04

[300 rows x 6 columns]