# Normalisation

Pourquoi normaliser ?
C'est une méthode qui permet de résoudre le problème d'ordre de grandeur des données en ajustant les valeurs des variables pour qu'elles se situent dans un intervalles spécifié, souvent entre 0 et 1, ou autour de la moyenne avec un ecart-type donné.

**Les avantages ? **


*   Comparabilité : permet de comparer avec d'autres modèles de données similaires
*   Optimisation des modélisations en ML


*   Stabilisation des modèles
*   Amélioration de l'interopérabilité

**Les méthodes: **



*   Min-max scalin
*   Standardisation = ramener les données à une valeur standard définie


*   Transformation en percentile

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

# Remplacez 'Mon_Dossier/mon_fichier.csv' par le chemin réel de votre fichier sur Google Drive
file_path = '/content/drive/My Drive/formation_personnelle/data_csv/base_clients.csv'

try:
    df = pd.read_csv(file_path, sep=";")
    print(f"Fichier '{file_path}' chargé avec succès.")
    display(df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier '{file_path}' n'a pas été trouvé. Veuillez vérifier le chemin.")
except Exception as e:
    print(f"Une erreur est survenue lors du chargement du fichier: {e}")

Mounted at /content/drive
Fichier '/content/drive/My Drive/formation_personnelle/data_csv/base_clients.csv' chargé avec succès.

  id_client genre  annee_naissance
0     C0001     f             1951
1     C0002     h             1964
2     C0003     f             1990
3     C0004     h             1973
4     C0005     f             1963

In [4]:
clients = df

#Nomalisation Min-max

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
# Là on demande au code de localiser la colonne qui correspond à l'année de naissance et de voir toutes
#toutes les autres colonnes differentes de celle-ci
xnum = clients.loc[:, clients.columns == "annee_naissance"]
xcat = clients.loc[:, clients.columns != "annee_naissance"]

In [7]:
#Initialiser l'échelle min et max
sc = MinMaxScaler()
xnum = pd.DataFrame(sc.fit_transform(xnum), columns=xnum.columns)
xnum

#Résultat: les valeurs sont normalisées entre 0 et 1

     annee_naissance
0           0.000000
1           0.224138
2           0.672414
3           0.379310
4           0.206897
..               ...
255         0.517241
256         0.879310
257         0.982759
258         0.810345
259         0.844828

[260 rows x 1 columns]

In [8]:
clients = pd.merge(xnum, xcat, left_index=True, right_index=True)
clients.head()

   annee_naissance id_client genre
0         0.000000     C0001     f
1         0.224138     C0002     h
2         0.672414     C0003     f
3         0.379310     C0004     h
4         0.206897     C0005     f

# Standardisation

In [9]:
clients.dropna()

     annee_naissance id_client genre
0           0.000000     C0001     f
1           0.224138     C0002     h
2           0.672414     C0003     f
3           0.379310     C0004     h
4           0.206897     C0005     f
..               ...       ...   ...
255         0.517241     C0256     h
256         0.879310     C0257     f
257         0.982759     C0258     f
258         0.810345     C0259     f
259         0.844828     C0260     h

[260 rows x 3 columns]

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
xnum = clients.loc[:, clients.columns == "annee_naissance"]
xcat = clients.loc[:, clients.columns != "annee_naissance"]

In [13]:
sc = StandardScaler()
xnum = pd.DataFrame(sc.fit_transform(xnum), columns=xnum.columns)
xnum

#

     annee_naissance
0          -1.655735
1          -0.914983
2           0.566522
3          -0.402154
4          -0.971964
..               ...
255         0.053694
256         1.250294
257         1.592179
258         1.022370
259         1.136332

[260 rows x 1 columns]

In [14]:
clients = pd.merge(xnum, xcat, left_index=True, right_index=True)
clients.head()

   annee_naissance id_client genre
0        -1.655735     C0001     f
1        -0.914983     C0002     h
2         0.566522     C0003     f
3        -0.402154     C0004     h
4        -0.971964     C0005     f