In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Remplacez 'Mon_Dossier/mon_fichier.csv' par le chemin réel de votre fichier sur Google Drive
file_path = '/content/drive/My Drive/SENEGAL/DATA/DATA_CSV/curiexplore-pays.csv'

try:
    df = pd.read_csv(file_path, sep=";")
    print(f"Fichier '{file_path}' chargé avec succès.")
    display(df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier '{file_path}' n'a pas été trouvé. Veuillez vérifier le chemin.")
except Exception as e:
    print(f"Une erreur est survenue lors du chargement du fichier: {e}")

Mounted at /content/drive
Fichier '/content/drive/My Drive/SENEGAL/DATA/DATA_CSV/curiexplore-pays.csv' chargé avec succès.

,iso3,name_en,name_fr,name_native,iso2,borders,flag,latlng,wikidata,bologne,...,ue28,g7,g20,geometry,ue_euro,oecd_obs,oecd_members_old,brics,code_num_3,cog
0,BEN,Benin,Bénin,Bénin,BJ,"BFA,NER,NGA,TGO",https://upload.wikimedia.org/wikipedia/commons...,"9.5, 2.25",Q962,False,...,False,False,False,"{""coordinates"": [[[2.691701694356254, 6.258817...",False,False,False,False,204.0,99327.0
1,CAN,Canada,Canada,Canada,CA,USA,https://upload.wikimedia.org/wikipedia/commons...,"60.0, -95.0",Q16,False,...,False,True,True,"{""coordinates"": [[[[-63.6645, 46.55001], [-62....",False,False,True,False,124.0,99401.0
2,MDA,Moldova (Republic of),Moldavie,Moldova,MD,"ROU,UKR",https://upload.wikimedia.org/wikipedia/commons...,"47.0, 29.0",Q217,True,...,False,False,False,"{""coordinates"": [[[26.619336785597795, 48.2207...",False,False,False,False,498.0,99151.0
3,MNG,Mongolia,Mongolie,Монгол улс,MN,"CHN,RUS",https://upload.wikimedia.org/wikipedia/commons...,"46.0, 105.0",Q711,False,...,False,False,False,"{""coordinates"": [[[87.7512642760767, 49.297197...",False,False,False,False,496.0,99242.0
4,ALB,Albania,Albanie,Shqipëria,AL,"MNE,GRC,MKD,KOS",https://upload.wikimedia.org/wikipedia/commons...,"41.0, 20.0",Q222,True,...,False,False,False,"{""coordinates"": [[[20.590247430104906, 41.8554...",False,False,False,False,8.0,99125.0

In [3]:
df.drop_duplicates() #Fonction drop_duplicates qui permet de supprimer les doublons

,iso3,name_en,name_fr,name_native,iso2,borders,flag,latlng,wikidata,bologne,...,ue28,g7,g20,geometry,ue_euro,oecd_obs,oecd_members_old,brics,code_num_3,cog
0,BEN,Benin,Bénin,Bénin,BJ,"BFA,NER,NGA,TGO",https://upload.wikimedia.org/wikipedia/commons...,"9.5, 2.25",Q962,False,...,False,False,False,"{""coordinates"": [[[2.691701694356254, 6.258817...",False,False,False,False,204.0,99327.0
1,CAN,Canada,Canada,Canada,CA,USA,https://upload.wikimedia.org/wikipedia/commons...,"60.0, -95.0",Q16,False,...,False,True,True,"{""coordinates"": [[[[-63.6645, 46.55001], [-62....",False,False,True,False,124.0,99401.0
2,MDA,Moldova (Republic of),Moldavie,Moldova,MD,"ROU,UKR",https://upload.wikimedia.org/wikipedia/commons...,"47.0, 29.0",Q217,True,...,False,False,False,"{""coordinates"": [[[26.619336785597795, 48.2207...",False,False,False,False,498.0,99151.0
3,MNG,Mongolia,Mongolie,Монгол улс,MN,"CHN,RUS",https://upload.wikimedia.org/wikipedia/commons...,"46.0, 105.0",Q711,False,...,False,False,False,"{""coordinates"": [[[87.7512642760767, 49.297197...",False,False,False,False,496.0,99242.0
4,ALB,Albania,Albanie,Shqipëria,AL,"MNE,GRC,MKD,KOS",https://upload.wikimedia.org/wikipedia/commons...,"41.0, 20.0",Q222,True,...,False,False,False,"{""coordinates"": [[[20.590247430104906, 41.8554...",False,False,False,False,8.0,99125.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,PAK,Pakistan,Pakistan,Pakistan,PK,"AFG,CHN,IND,IRN",https://upload.wikimedia.org/wikipedia/commons...,"30.0, 70.0",Q843,False,...,False,False,False,"{""coordinates"": [[[75.15802778514092, 37.13303...",False,True,False,False,586.0,99213.0
212,PRY,Paraguay,Paraguay,Paraguay,PY,"ARG,BOL,BRA",https://upload.wikimedia.org/wikipedia/commons...,"-23.0, -58.0",Q733,False,...,False,False,False,"{""coordinates"": [[[-62.685057135657885, -22.24...",False,False,False,False,600.0,99421.0
213,ROU,Romania,Roumanie,România,RO,"BGR,HUN,MDA,SRB,UKR",https://upload.wikimedia.org/wikipedia/commons...,"46.0, 25.0",Q218,True,...,True,False,False,"{""coordinates"": [[[22.710531447040495, 47.8821...",False,True,False,False,642.0,99114.0
214,SVN,Slovenia,Slovénie,Slovenija,SI,"AUT,HRV,ITA,HUN",https://upload.wikimedia.org/wikipedia/commons...,"46.11666666, 14.81666666",Q215,True,...,True,False,False,"{""coordinates"": [[[13.806475457421527, 46.5093...",True,False,False,False,705.0,99145.0
215,ZAF,South Africa,Afrique du Sud,South Africa,ZA,"BWA,LSO,MOZ,NAM,SWZ,ZWE",https://upload.wikimedia.org/wikipedia/commons...,"-29.0, 24.0",Q258,False,...,False,False,True,"{""coordinates"": [[[31.521001417778876, -29.257...",False,False,False,True,710.0,99303.0

In [4]:
df.drop_duplicates(subset='iso2',keep='last')

,iso3,name_en,name_fr,name_native,iso2,borders,flag,latlng,wikidata,bologne,...,ue28,g7,g20,geometry,ue_euro,oecd_obs,oecd_members_old,brics,code_num_3,cog
0,BEN,Benin,Bénin,Bénin,BJ,"BFA,NER,NGA,TGO",https://upload.wikimedia.org/wikipedia/commons...,"9.5, 2.25",Q962,False,...,False,False,False,"{""coordinates"": [[[2.691701694356254, 6.258817...",False,False,False,False,204.0,99327.0
1,CAN,Canada,Canada,Canada,CA,USA,https://upload.wikimedia.org/wikipedia/commons...,"60.0, -95.0",Q16,False,...,False,True,True,"{""coordinates"": [[[[-63.6645, 46.55001], [-62....",False,False,True,False,124.0,99401.0
2,MDA,Moldova (Republic of),Moldavie,Moldova,MD,"ROU,UKR",https://upload.wikimedia.org/wikipedia/commons...,"47.0, 29.0",Q217,True,...,False,False,False,"{""coordinates"": [[[26.619336785597795, 48.2207...",False,False,False,False,498.0,99151.0
3,MNG,Mongolia,Mongolie,Монгол улс,MN,"CHN,RUS",https://upload.wikimedia.org/wikipedia/commons...,"46.0, 105.0",Q711,False,...,False,False,False,"{""coordinates"": [[[87.7512642760767, 49.297197...",False,False,False,False,496.0,99242.0
4,ALB,Albania,Albanie,Shqipëria,AL,"MNE,GRC,MKD,KOS",https://upload.wikimedia.org/wikipedia/commons...,"41.0, 20.0",Q222,True,...,False,False,False,"{""coordinates"": [[[20.590247430104906, 41.8554...",False,False,False,False,8.0,99125.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,PAK,Pakistan,Pakistan,Pakistan,PK,"AFG,CHN,IND,IRN",https://upload.wikimedia.org/wikipedia/commons...,"30.0, 70.0",Q843,False,...,False,False,False,"{""coordinates"": [[[75.15802778514092, 37.13303...",False,True,False,False,586.0,99213.0
212,PRY,Paraguay,Paraguay,Paraguay,PY,"ARG,BOL,BRA",https://upload.wikimedia.org/wikipedia/commons...,"-23.0, -58.0",Q733,False,...,False,False,False,"{""coordinates"": [[[-62.685057135657885, -22.24...",False,False,False,False,600.0,99421.0
213,ROU,Romania,Roumanie,România,RO,"BGR,HUN,MDA,SRB,UKR",https://upload.wikimedia.org/wikipedia/commons...,"46.0, 25.0",Q218,True,...,True,False,False,"{""coordinates"": [[[22.710531447040495, 47.8821...",False,True,False,False,642.0,99114.0
214,SVN,Slovenia,Slovénie,Slovenija,SI,"AUT,HRV,ITA,HUN",https://upload.wikimedia.org/wikipedia/commons...,"46.11666666, 14.81666666",Q215,True,...,True,False,False,"{""coordinates"": [[[13.806475457421527, 46.5093...",True,False,False,False,705.0,99145.0
215,ZAF,South Africa,Afrique du Sud,South Africa,ZA,"BWA,LSO,MOZ,NAM,SWZ,ZWE",https://upload.wikimedia.org/wikipedia/commons...,"-29.0, 24.0",Q258,False,...,False,False,True,"{""coordinates"": [[[31.521001417778876, -29.257...",False,False,False,True,710.0,99303.0