1- Le label encoding permet d'attribuer une valeur numérique à une valeur qui, initialement est une catégorie textuelle.

2- Deuxième méthode (One-Hote-encoding):

In [1]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Remplacez 'Mon_Dossier/mon_fichier.csv' par le chemin réel de votre fichier sur Google Drive
file_path = '/content/drive/My Drive/formation_personnelle/data_csv/base_clients.csv'

try:
    df = pd.read_csv(file_path, sep=";")
    print(f"Fichier '{file_path}' chargé avec succès.")
    display(df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier '{file_path}' n'a pas été trouvé. Veuillez vérifier le chemin.")
except Exception as e:
    print(f"Une erreur est survenue lors du chargement du fichier: {e}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Fichier '/content/drive/My Drive/formation_personnelle/data_csv/base_clients.csv' chargé avec succès.

  id_client genre  annee_naissance
0     C0001     f             1951
1     C0002     h             1964
2     C0003     f             1990
3     C0004     h             1973
4     C0005     f             1963

Label encoding

In [5]:
#S'assurer d'abnord que le jeux de données ne contient aucune valeur manquante en supprimant toutes celles qui peuvent exister.
client = df.dropna()
client.dtypes

id_client          object
genre              object
annee_naissance     int64
dtype: object

In [6]:
client.head()

  id_client genre  annee_naissance
0     C0001     f             1951
1     C0002     h             1964
2     C0003     f             1990
3     C0004     h             1973
4     C0005     f             1963

In [8]:
#Convertir les valeurs textuelles en valeurs numériques (f et h)
from sklearn.preprocessing import LabelEncoder

#Création de l'instance
label_encoder = LabelEncoder()
#Appliquer le label encoder pour convertir les valeurs 'f' et 'h' en 0 et 1
client['genre'] = label_encoder.fit_transform(client['genre'])

#Affichier le dataFrame pour vérifier la conversion
client

    id_client  genre  annee_naissance
0       C0001      0             1951
1       C0002      1             1964
2       C0003      0             1990
3       C0004      1             1973
4       C0005      0             1963
..        ...    ...              ...
255     C0256      1             1981
256     C0257      0             2002
257     C0258      0             2008
258     C0259      0             1998
259     C0260      1             2000

[260 rows x 3 columns]

In [10]:
client['genre'].value_counts()

genre
1    132
0    128
Name: count, dtype: int64

One Hot encoding

In [12]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore')

#Appliquer l'encodage sur la colonne 'genre'
encoder_df = pd.DataFrame(encoder.fit_transform(client[['genre']]).toarray())
encoder_df

#Créer un nouveau DataFrame avec les données encodées

       0    1
0    1.0  0.0
1    0.0  1.0
2    1.0  0.0
3    0.0  1.0
4    1.0  0.0
..   ...  ...
255  0.0  1.0
256  1.0  0.0
257  1.0  0.0
258  1.0  0.0
259  0.0  1.0

[260 rows x 2 columns]